config/routes.rb
ReportBook::Application.routes.draw do

  resources :user, :only => [:index, :show, :edit, :destroy, :update]

  resources :home, :only => [:index, :show]
  authenticated :user do
    root :to => 'probations#index'
  end

  devise_for :users

  resources :probations do
    resources :images, :only => [:create, :destroy]
    resources :dailies do
      resources :comments, :only => :create
    end
  end

  root :to => 'home#index'

end

app/models/probation.rb
class Probation < ActiveRecord::Base
  attr_accessible :finished_at, :firm_name, :probation_name, :probation_type, :started_at, :user_id
  validate :valid_date? => {:on => :create}

  def valid_date?
    if finished_at < started_at
      errors.add(:finished_at, "invalid! become started at <= finished at  ")
    elsif DateTime.now.to_date > started_at
      errors.add(:started_at, "invalid! become started at >= #{DateTime.now.to_date} ")
    elsif Probation.where("(finished_at BETWEEN ? AND ?) or (started_at BETWEEN ? AND ?) or (started_at <= ?
                            and finished_at >= ? )", started_at, finished_at, started_at, finished_at, started_at,
                              finished_at).size > 0
      errors.add(:started_at, "There is another probation betwen this dates ")
    end
  end
  has_many :daily
  has_many :image
  belongs_to :user
end

app/controllers/probations_controller.rb
class ProbationsController < ApplicationController

  before_filter :authenticate_user!
  before_filter 'kontrol', :only => [:edit, :update, :destroy]

  def kontrol
    @temp = Probation.find(params[:id])
    if @temp.user_id != session[:user].id and current_user.role != "admin"
      redirect_to probations_path
    end
  end

  def index
    if params[:us_id] != nil
      session[:user] = User.find(params[:us_id])
      params[:us_id] = nil
      redirect_to probations_path
      return
    end
    @probation = Probation.where(:user_id => session[:user].id).paginate(:page => params[:page_1], :per_page => 5).order("finished_at DESC")
    @probation_all = Probation.where('user_id != ?', session[:user].id).paginate(:page => params[:page_2], :per_page => 5).order("finished_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @probation }
    end
  end

  def edit
    @probation = Probation.find(params[:id])

  end

  def new
    if User.find(session[:user].id).university.nil?
      #if session[:user].id == current_user.id
        redirect_to edit_user_registration_path, :notice => "You must complete your profil "
      #else
      #  redirect_to edit_user_path(session[:user])
      #end
      return
    end
    @probation = Probation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @probation }
    end
  end

  def show
    @probation = Probation.find(params[:id])
    if @probation.user_id == session[:user].id
      @daily = @probation.daily.paginate(:page => params[:page], :per_page => 5)
      @daily_pdf = @probation.daily.all
    else
      @daily = @probation.daily.where(:status => true).paginate(:page => params[:page], :per_page => 5)
      @daily_pdf = @probation.daily.where(:status => true)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @probation }
      format.pdf  { ppdf }
    end
  end

  def update
    @probation = Probation.find(params[:id])
    #@probation_temp =  Probation.new(params[:probation])
    #if @probation_temp.started_at > @probation_temp.finished_at
    # @probation_temp.destroy
    #render('edit')
    #return
    #end
    respond_to do |format|
      if @probation.update_attributes(params[:probation])
        format.html { redirect_to @probation, :notice => 'Probations was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @probation.errors, :status => :unprocessable_entity }
      end
    end
  end

  def create
    @probation = Probation.new(params[:probation])
    @probation.user_id = session[:user].id
    respond_to do |format|
      if @probation.save
        format.html { redirect_to @probation, :notice => 'Probation was successfully created.' }
        format.json { render :json => @probation, :status => :created, :location => @probation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @probation.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @probation = Probation.find(params[:id])
    @daily = @probation.daily

    @daily.each do  |daily|
      @comment = daily.comment
      @comment.each do  |comment|
        comment.destroy
      end
      daily.destroy
    end

    @image = @probation.image
    @image.each do |im|
      File.delete("app/assets/images/#{im.path}")
      im.destroy
    end
    @probation.destroy

    respond_to do |format|
      format.html { redirect_to probations_url, :notice => 'Probation was successfully deleted.' }
      format.json { head :ok }
    end
  end

  def ppdf
    pdf = Prawn::Document.new
    pdf.text  "#{@probation.probation_name.upcase}", :size => 15, :style => :bold, :align => :center
    pdf.text "( #{@probation.started_at} - #{@probation.finished_at} )", :size => 10, :align => :center
    pdf.move_down(30)

    @daily_pdf.each do |daily|
      pdf.draw_text "Subject : ", :size => 13, :style => :bold, :at => [20, 650]
      pdf.text_box "#{daily.subject.capitalize}     (#{daily.created_at.to_date})", :size => 12, :at => [80, 657]
      pdf.draw_text "Content : ", :size => 13, :style => :bold, :at => [20, 630]
      pdf.text_box "#{daily.content.capitalize}", :size => 12, :at => [80, 637], :width => 500
      if daily.id != @daily_pdf.last.id
        pdf.start_new_page
      end
    end
    pdf.move_down(10)
    filename = File.join(Rails.root, "app/report", "document.pdf")
    pdf.render_file filename
    send_file filename, :filename => "document.pdf", :type => "application/pdf"
  end

end

app/helpers/probations_helper.rb
module ProbationsHelper
end

app/views/probations/_form.html.erb
<%= simple_form_for(@probation, :validate => true, :html => {:class => 'form-vertical validate' }) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :probation_name, :required => true %>
      <%= f.input :firm_name, :required => true %>
      <%= f.input :probation_type, :required => true %>
      <% if @probation.id == nil %>
        <%= f.input :started_at, :required => false, :input_html => { :style => "width: 70px;"}  %>
        <%= f.input :finished_at, :required => false, :input_html => { :style => "width: 70px;"} %>
      <% end %>
    </div>
    <div class="form-actions">
      <%= f.submit :submit %>
    </div>
<% end %>

app/views/probations/edit.html.erb
<h1>Editing Probation</h1>

<%= render 'form' %>

<%= link_to 'Show', @probation %> |
<%= link_to 'Back', probations_path %>

app/views/probations/index.html.erb
  <h2>My Probation</h2>

      <%= link_to("Add New Probation", new_probation_path, :class => '') %>


  <div><%= pluralize(@probation.size, 'probation') %> found</div>
  <table class="#">
    <tr class="#">
      <th>Probation Name</th>
      <th>Firm Name</th>
      <th>Probation Type</th>
      <th>Start Date</th>
      <th>Finish Date</th>
      <th>Daily Count</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
    <% @probation.each do |probation| %>
        <tr class="#">
          <td><%= probation.probation_name %></td>
          <td><%= probation.firm_name %></td>
          <td><%= probation.probation_type %></td>
          <td><%= probation.started_at %></td>
          <td><%= probation.finished_at %></td>
          <td><%= probation.daily.size%></td>
          <td>
            <%= link_to("Show", probation, :class => '#') %>
          </td>
          <td>
            <%= link_to("Edit", edit_probation_path(probation), :class => '#') %>
          </td>
          <td>
            <%= link_to 'Destroy', probation, confirm: 'Are you sure?', method: :delete %>
          </td>
          <td>
            <%= link_to 'Pdf', probation_path(probation, :format => 'pdf')%>
          </td>
        </tr>
    <% end %>
  </table>
  <%= will_paginate @probation, :param_name => 'page_1', :renderer => BootstrapPagination::Rails %>

  <hr/>
  <h2>Other Probation</h2>
  <table class="#">
    <tr class="#">
      <th>Probation Name</th>
      <th>Firm Name</th>
      <th>Probation Type</th>
      <th>Start Date</th>
      <th>Finish Date</th>
      <th>Daily Count</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>


    </tr>
    <% @probation_all.each do |probation| %>
        <tr class="#">
          <td><%= probation.probation_name %></td>
          <td><%= probation.firm_name %></td>
          <td><%= probation.probation_type %></td>
          <td><%= probation.started_at %></td>
          <td><%= probation.finished_at %></td>
          <td><% if current_user.role == "admin" %>
            <%= probation.daily.where(:status => true).size %>
              <% else %>
                <%= probation.daily.all.size  %>
              <% end %>  </td>
          <td>
            <%= link_to("Show", probation, :class => '#') %>
          </td>
          <td>
            <%= link_to 'Pdf', probation_path(probation, :format => 'pdf')%>
          </td>
         </tr>
    <% end %>
  </table>
  <%= will_paginate @probation_all, :param_name => 'page_2', :renderer => BootstrapPagination::Rails %>

app/views/probations/new.html.erb
<h2>Create Probation</h2>

<%= render 'form' %>
<%= link_to 'Back', probations_path %>

app/views/probations/show.html.erb
  <p id="notice"><%= notice %></p>

  <h2>Show Probation</h2>
  <table width="80%"  >
    <tr>
      <th>Probation Name</th>
      <th>Firm Name</th>
      <th>Probation Type</th>
      <th>Start Date</th>
      <th>Finish Date</th>

    </tr>
    <tr align="center">
      <td><%= @probation.probation_name %></td>
      <td><%= @probation.firm_name %></td>
      <td><%= @probation.probation_type %></td>
      <td><%= @probation.started_at %></td>
      <td><%= @probation.finished_at %></td>
    </tr>
    <tr>
      <td colspan="3">
        <br/>
        <%= link_to 'Back', probations_path %>
      </td>
      <td colspan="2">
        <br/>
        <% if @probation.image.size < 20 and @probation.user_id == session[:user].id  %>
            <%= render 'images/form'  %>
        <% end %>
      </td>
    </tr>
  </table>


<hr/>
<div >
 <% if  @probation.user_id == session[:user].id %>
  <table width="100%">

     <%@temp = 0 %>
  <% @probation.image.each do |im| %>
        <% if im.path == nil %>
            <%break%>
        <% end %>
      <% if @temp % 10 == 0 %>
            <tr>
      <% end %>
      <td align="center">

        <%= image_tag("#{im.path}", :alt => "", :size => "100x100" ) %>  <br/>
        <%= link_to 'X', probation_image_path(@probation, im), confirm: 'Are you sure?', method: :delete %>


      </td>
        <% @temp += 1 %>

  <% end %>
      </tr>
  </table>
  <% end %>
</div>
<hr/>

  <h3>Dailies</h3>
  <% if  @probation.user_id == session[:user].id %>
    <%= link_to("Add New Daily", new_probation_daily_path(@probation), :class => '') %>
      <% end %>
  <div><%= pluralize(@daily.size, 'daily') %> found</div>

  <table class="#">
    <tr class="#">
      <th>Subject</th>
      <th>Status</th>
      <th>Create Date</th>
      <th>Comment Count</th>

      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
    <% @daily.each do |daily| %>
        <tr class="#">
          <td><%= daily.subject %></td>
          <td><%= daily.status ? 'Public' : 'Private' %></td>
          <td><%= daily.created_at.to_date %></td>
          <td><%= daily.comment.size%></td>

          <td>
            <%= link_to("Show", probation_daily_path(@probation, daily), :class => '#') %>
          </td>
          <td>
            <% if  @probation.user_id == session[:user].id %>
            <%= link_to("Edit", edit_probation_daily_path(@probation, daily), :class => '#') %>
                <% end %>
          </td>
          <td>
            <% if  @probation.user_id == session[:user].id %>
            <%= link_to 'Destroy', probation_daily_path(@probation, daily), confirm: 'Are you sure?', method: :delete %>
                <% end %>
          </td>
          <td>
            <% if  @probation.user_id == session[:user].id or daily.status == true %>
                <%= link_to 'Pdf', probation_daily_path(@probation, daily, :format => 'pdf')%>
            <% end %>
          </td>
        </tr>

    <% end %>

  </table>
<%= will_paginate @daily, :renderer => BootstrapPagination::Rails %>