config/routes.rb
ReportBook::Application.routes.draw do

  resources :user, :only => [:index, :show, :edit, :destroy, :update]

  resources :home, :only => [:index, :show]
  authenticated :user do
    root :to => 'probations#index'
  end

  devise_for :users

  resources :probations do
    resources :images, :only => [:create, :destroy]
    resources :dailies do
      resources :comments, :only => :create
    end
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:url] = "home"
    @daily = Daily.where(:status => true).paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
  end

  def show
    @daily = Daily.find(params[:id])
    @comment = @daily.comment.paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    respond_to do |format|
      format.html # show.html.erb
      format.pdf  { ppdf(@daily) }
    end
  end

  def ppdf(daily)
    pdf = Prawn::Document.new
    pdf.text  "#{daily.probation.probation_name.upcase}", :size => 15, :style => :bold, :align => :center
    pdf.text "( #{daily.probation.started_at} - #{daily.probation.finished_at} )", :size => 10, :align => :center
    pdf.move_down(30)


      pdf.draw_text "Subject : ", :size => 13, :style => :bold, :at => [20, 650]
      pdf.text_box "#{daily.subject.capitalize}     (#{daily.created_at.to_date})", :size => 12, :at => [80, 657]
      pdf.draw_text "Content : ", :size => 13, :style => :bold, :at => [20, 630]
      pdf.text_box "#{daily.content.capitalize}", :size => 12, :at => [80, 637], :width => 500

    pdf.move_down(10)
    filename = File.join(Rails.root, "app/report", "document.pdf")
    pdf.render_file filename
    send_file filename, :filename => "document.pdf", :type => "application/pdf"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
  <table width="100%" >
    <tr>
      <th>Subject</th>
      <th>Content</th>
      <th>Create Date</th>
      <th>Comment Count</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>


    </tr>
    <% @daily.each do |daily| %>
        <tr>
          <td><%= daily.subject %></td>
          <td><%= daily.content %></td>
          <td><%= daily.created_at.to_date %></td>
          <td><%= daily.comment.size  %></td>
          <td><%= link_to("Show", home_path(daily)) %></td>
          <td><%= link_to("Pdf", home_path(daily, :format => 'pdf')) %></td>
        </tr>
    <% end %>
  </table>
  <%= will_paginate @daily, :renderer => BootstrapPagination::Rails %>

app/views/home/show.html.erb
<table >
  <tr>
    <th>Subject</th>
    <th>Content</th>
    <th>Create Date</th>


  </tr>
  <tr>
    <td><%= @daily.subject %></td>
    <td><%= @daily.content %></td>
    <td><%= @daily.created_at.to_date %></td>
  </tr>
</table>

<hr/>


<h3>Comments</h3>
<table class="#">
  <tr class="#">
    <th>Comment</th>
    <th>Created at</th>
  </tr>
  <% @comment.each do |comment| %>
      <tr class="#">
        <td><%= comment.comment %></td>
        <td><%= comment.created_at.strftime("%B  %A  %H:%M:%S")  %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @comment, :renderer => BootstrapPagination::Rails %>